{{- if include "context-foundry-fusion.ownsSecret" . }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "context-foundry-fusion.fullname" . }}
  labels:
    {{- include "context-foundry-fusion.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- $s := .Values.sinks.takWs.auth.oidcClientSecret }}
  {{- if and $s.value (not $s.secretName) }}
  {{ $s.secretKey }}: {{ $s.value | quote }}
  {{- end }}
  {{- $b := .Values.sinks.takWs.auth.bearerToken }}
  {{- if and $b.value (not $b.secretName) }}
  {{ $b.secretKey }}: {{ $b.value | quote }}
  {{- end }}
{{- end }}
